module.exports = {
  content: {
    robots: "meta[name='robots']",
    description: "meta[name='description']",
  },
  textContent: {
    title: "title",
    h1: "h1",
    h2: "h2",
    h3: "h3",
    h4: "h4",
    h5: "h5",
    h6: "h6",
    p: "p",
    //a: "a",
    span: "span",
    li: "li",
    ul: "ul",
    ol: "ol",
    dl: "dl",
    dt: "dt",
    dd: "dd",
    blockquote: "blockquote",
    pre: "pre",
    code: "code",
    table: "table",
    thead: "thead",
    tbody: "tbody",
    tr: "tr",
    th: "th",
    td: "td",
    img: "img",
    iframe: "iframe",
    video: "video",
    audio: "audio",
    source: "source",
    embed: "embed",
    object: "object",
    param: "param",
    map: "map",
    area: "area",
    form: "form",
    fieldset: "fieldset",
    legend: "legend",
    label: "label",
    input: "input",
    button: "button",
    select: "select",
    datalist: "datalist",
    optgroup: "optgroup",
    option: "option",
    textarea: "textarea",
    keygen: "keygen",
    output: "output",
    progress: "progress",
    meter: "meter",
    details: "details",
    summary: "summary",
    menu: "menu",
    menuitem: "menuitem",
    dialog: "dialog",
    canvas: "canvas",
    listing: "listing",
    xmp: "xmp",
    
  },
  href: {
    links: "a",
    canonical: "link[rel='canonical']",
    alternateMobile: "link[media='only screen and (max-width: 640px)']",
    prevPagination: "link[rel='prev']",
    nextPagination: "link[rel='next']",
    amp: "link[rel='amphtml']"
  },
  outerHTML: {
    hreflang: "link[hreflang]"
  }
}
